image:
- Ubuntu

configuration:
  - Release

platform:
  - x86
  - x64

install:
  - wget https://dl.bintray.com/boostorg/release/1.69.0/source/boost_1_69_0.tar.gz -O /tmp/boost.tar.gz
  - tar -xf /tmp/boost.tar.gz -C /tmp
  - export BOOST_ROOT=/tmp/boost_1_69_0
  - cd $BOOST_ROOT
  - ./bootstrap.sh --with-libraries=system,chrono,thread
  - ./b2

build_script:
  - cd %APPVEYOR_BUILD_FOLDER%/build/linux
  - python build_linux_all.py

cache: '%APPVEYOR_BUILD_FOLDER%/release/nakama-cpp-sdk'
