steps:
- name: 'gcr.io/heroiclabs-shared/nakama-cpp:ubuntu1804-boost169-cmake3155'
  volumes:
  - name: 'vol1'
    path: '/persistent_volume'
  args: ['git', 'clone', '--recurse-submodules', 'git://github.com/heroiclabs/nakama-cpp.git']
- name: 'gcr.io/heroiclabs-shared/nakama-cpp:ubuntu1804-boost169-cmake3155'
  volumes:
  - name: 'vol1'
    path: '/persistent_volume'
  args: ['python', 'build_linux_all.py']
  dir: 'nakama-cpp/build/linux'
- name: gcr.io/cloud-builders/gsutil
  args: ['cp', '-r', 'nakama-cpp/release/nakama-cpp-sdk', 'gs://nakama-cpp/release']
  timeout: 3600s
timeout: 7200s
